mod.name=PolyTime
mod.id=polytime
mod.version=1.2.0
mod.group=org.polyfrost

publish.modrinth=m3kNp1iP

loomx.loom_version=1.17-SNAPSHOT
loader_version=0.19.2

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.parallel.threads=4
org.gradle.jvmargs=-Xmx4G

# Fix YALMM
fabric.loom.dropNonIntermediateRootMethods=true
